name: Hello Workflows

on: 
  push: 
    branches:
      - feat/ci-cd

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone codebase
        uses: actions/checkout@v4 # clone codebase

      - name: Set up Node version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Kiểm tra thư mục
        run: ls -la

      - name: Kiểm tra phiên bản Node
        run: node -v