name: Hello Workflows

on: 
  push: 
    branches:
      - feat/ci-cd

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node version 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check directories
        run: ls
      - name: Check node version
        run: node -v